Controllers/CrearUsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvc.Controllers
{
    public class CrearUsuarioController : Controller
    {
        // GET: CrearUsuario
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/GitHubController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvc.Controllers
{
    public class GitHubController : Controller
    {
        // GET: GitHub
        public ActionResult Index()
        {
            ViewBag.cantidad_archivos_repositorio_github = ConfigurationManager.AppSettings["cantidad_archivos_repositorio_github"];

            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvc.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        
    }
}

Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvc.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/wsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace mvc.Controllers
{
    public class wsController : Controller
    {
        public string get_github()
        {
            StreamReader StreamReader_ = null;

            string url_api = String.Format(ConfigurationManager.AppSettings["config_github"]);
            
            

            var requestWS = (HttpWebRequest)WebRequest.Create(url_api);
            requestWS.Timeout = 60000;
            requestWS.Method = "GET";
            requestWS.ContentType = "text/plain;charset=utf-8";

            HttpWebResponse resprequestWSget_usuario = requestWS.GetResponse() as HttpWebResponse;
            Stream respStreamBrake1 = resprequestWSget_usuario.GetResponseStream();
            StreamReader_ = new StreamReader(respStreamBrake1, Encoding.UTF8);

            url_api = StreamReader_ == null ? "" : StreamReader_.ReadToEnd();
            return url_api;
        }

        [HttpPost]
        public string set_CrearUsuario(string name, string email, string password)
        {
            StreamReader StreamReader_ = null;

            string url_api = String.Format(ConfigurationManager.AppSettings["set_CrearUsuario"], name, email, password);

            var requestWS = (HttpWebRequest)WebRequest.Create(url_api);
            requestWS.Timeout = 60000;
            requestWS.Method = "GET";
            requestWS.ContentType = "text/plain;charset=utf-8";

            HttpWebResponse resprequestWSget_usuario = requestWS.GetResponse() as HttpWebResponse;
            Stream respStreamBrake1 = resprequestWSget_usuario.GetResponseStream();
            StreamReader_ = new StreamReader(respStreamBrake1, Encoding.UTF8);

            url_api = StreamReader_ == null ? "" : StreamReader_.ReadToEnd();
            return url_api;
        }

        [HttpPost]
        public string get_Login(string email, string password)
        {
            StreamReader StreamReader_ = null;

            string url_api = String.Format(ConfigurationManager.AppSettings["get_Login"], email, password);

            var requestWS = (HttpWebRequest)WebRequest.Create(url_api);
            requestWS.Timeout = 60000;
            requestWS.Method = "GET";
            requestWS.ContentType = "text/plain;charset=utf-8";

            HttpWebResponse resprequestWSget_usuario = requestWS.GetResponse() as HttpWebResponse;
            Stream respStreamBrake1 = resprequestWSget_usuario.GetResponseStream();
            StreamReader_ = new StreamReader(respStreamBrake1, Encoding.UTF8);

            url_api = StreamReader_ == null ? "" : StreamReader_.ReadToEnd();
            return url_api;
        }




    }
}

Views/CrearUsuario/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<script src="~/Content/js/CrearUsuario.js"></script>
<div style="background-color:#F2F2F2;">
    <br /><br />

    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-1 colxs-1">
        </div>
        <div class="col-lg-4 col-md-4 col-sm-10 colxs-10">
            <div class="col-lg-12 col-md-12 col-sm-12 colxs-12 margen_login" style="background-color:#ffffff;">

                <form method="post" action="/Usuario/SignOn" id="formularioUsuario">
                    <h3 class="form-title">Crear Usuario</h3>


                    <div class="form-group" style="text-align:left;">
                        <i class="fa fa-user"></i>
                        <label class="control-label" for="name">Escribe tu Nombre</label>
                        <div class="rut-container"><input class="form-control placeholder-no-fix input_rut" type="text" autocomplete="off" placeholder="david" id="name" name="name" value="" maxlength="100" required="required"></div>
                    </div>

                    <div class="form-group" style="text-align:left;">
                        <i class="fa fa-user"></i>
                        <label class="control-label" for="username">Escribe tu email</label>
                        <div class="rut-container"><input class="form-control placeholder-no-fix input_rut" type="text" autocomplete="off" placeholder="nombreusuario@gmail.com" id="username" name="username" value="" maxlength="40" required="required"></div>
                    </div>

                    <div class="form-group" style="text-align:left;">
                        <i class="fa fa-lock"></i>
                        <label for="password" class="control-label visible-ie8 visible-ie9">Escribe tu contraseña</label>
                        <input class="form-control placeholder-no-fix" type="password" autocomplete="off" placeholder="Password" id="password" name="password" value="">
                    </div>
                    <div class="form-group" style="text-align:left;">
                        <i class="fa fa-lock"></i>
                        <label for="password2" class="control-label visible-ie8 visible-ie9">Vuelve a escribir la contraseña</label>
                        <input class="form-control placeholder-no-fix" type="password" autocomplete="off" placeholder="Password" id="password2" name="password2" value="">
                    </div>

                    <div class="form-actions" style="text-align:right;">
                        <button type="button" class="btn btn-danger btn-lg" id="buttonsignon" onclick="crear_usuario()">
                            Crear Usuario<i class="fa fa-sign-in" aria-hidden="true"></i>
                        </button>
                    </div>


                    <div style="text-align:right; padding-top:40px;">
                        <div id="resultado_login1" class="message"></div>
                        <div id="resultado_login2" class="message"></div>
                        <div id="resultado_login3" class="message"></div>
                        <div id="resultado_login4" class="message"></div>
                        <div id="resultado_login5" class="message"></div>
                    </div>

                    <br><br><br><br>
                </form>
            </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-1 colxs-1">
        </div>
    </div>
    <br /><br /><br /><br /><br />
</div>



<input type="hidden" id="set_CrearUsuario" value="@Url.Action("set_CrearUsuario", "WS")" />

Views/GitHub/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<script src="~/Content/js/GitHub.js"></script>

<div style="background-color:#F2F2F2;">
    <center><h2>GitHub</h2></center>


    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-1 colxs-1">
        </div>
        <div class="col-lg-4 col-md-4 col-sm-10 colxs-10">
            <div class="col-lg-12 col-md-12 col-sm-12 colxs-12 margen_login" style="background-color:#ffffff;">

                <form method="post" action="/Usuario/SignOn" id="formularioUsuario">
                    <div class="form-actions" style="text-align:center;">
                        <br /><br /><br />
                        <button type="button" class="btn btn-danger btn-lg" id="buttonsignon" onclick="get_github()">
                            Obtener Repositorio de github
                        </button>
                    </div>


                    <div style="text-align:left; padding-top:40px;">
                        <div id="resultado_login1" class="message"></div>
                        <div id="header">
                            <ul class="tabs">
                            </ul>
                        </div>

                    </div>

                    <br><br><br><br>
                </form>
            </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-1 colxs-1">
        </div>
    </div>
    <br /><br /><br /><br /><br />
</div>


<input type="hidden" id="get_github" value="@Url.Action("get_github", "WS")" />
<input type="hidden" id="cantidad_archivos_repositorio_github" value="@ViewBag.cantidad_archivos_repositorio_github" />

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-md-4">
        <h3>Bienvenido</h3>
    </div>
</div>

Views/Login/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<script src="~/Content/js/Login.js"></script>
<div style="background-color:#F2F2F2;">
    <center><h2>Login</h2></center>


    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-1 colxs-1">
        </div>
        <div class="col-lg-4 col-md-4 col-sm-10 colxs-10">
            <div class="col-lg-12 col-md-12 col-sm-12 colxs-12 margen_login" style="background-color:#ffffff;">

                <form method="post" action="/Usuario/SignOn" id="formularioUsuario">
                    <h3 class="form-title">Ingresar</h3>
                    <div class="form-group" style="text-align:left;">
                        <i class="fa fa-user"></i>
                        <label class="control-label" for="username">Escribe email</label>
                        <div class="rut-container"><input class="form-control placeholder-no-fix input_rut" type="text" autocomplete="off" placeholder="nombreusuario@gmail.com" id="username" name="username" value="" maxlength="40" required="required"></div>
                    </div>
                    <div class="form-group" style="text-align:left;">
                        <i class="fa fa-lock"></i>
                        <label for="password" class="control-label visible-ie8 visible-ie9">Escribe tu contraseña</label>
                        <input class="form-control placeholder-no-fix" type="password" autocomplete="off" placeholder="Password" id="password" name="password" value="">
                    </div>
                    <div class="form-actions" style="text-align:right;">
                        <button type="button" class="btn btn-danger btn-lg" id="buttonsignon" onclick="logear()">
                            Ingresar <i class="fa fa-sign-in" aria-hidden="true"></i>
                        </button>
                    </div>
                    
                    
                    <div style="text-align:right; padding-top:40px;">
                        <div id="resultado_login1" class="message"></div>
                        <div id="resultado_login2" class="message"></div>
                        <div id="resultado_login3" class="message"></div>
                    </div>
                    
                    <br><br><br><br>
                </form>
            </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-1 colxs-1">
        </div>
    </div>
    <br /><br /><br /><br /><br />
</div>



<input type="hidden" id="get_Login" value="@Url.Action("get_Login", "WS")" />

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @*<script src="~/Content/jquery-3.5.1.js"></script>*@

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Login", "Index", "Login")</li>
                    <li>@Html.ActionLink("GitHub", "Index", "GitHub")</li>
                    <li>@Html.ActionLink("Crear Usuario", "Index", "CrearUsuario")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)



    <link href="~/Content/lib/jqueryui/jquery-ui.css" rel="stylesheet" />

    <script src="~/Content/lib/jqueryui/jquery-ui.js"></script>
    <script src="~/Content/lib/jqueryui/jquery.blockUI.js"></script>
</body>
</html>